passwd:
  users:
    - name: core
      ssh_authorized_keys:
        # cat ~/rke-rancher/rke-ecdsa.pub
        - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAFoHGL2y7gDaRObMhcs/coPsLgOllAQicAu2Tja3fPW6CKZ4tMoDeMXZ/A2Wi/w9OtiTD7aAn1b51ZyaL3rSGyc3wDL94SQgOPKDIRaJgF5zpgKRBM3C0Qrt1Vc7pO4qR3GJoWq90k+DJSFoEiS52t2exqhrUlUmjsEqsvYN+IzgYo6+g==

# Source: https://kinvolk.io/docs/flatcar-container-linux/latest/setup/storage/mounting-storage/#use-attached-storage-for-docker
# Don't wipe so that Longhorn volumes will persist across reboots
storage:
  filesystems:
    - name: lib
      mount:
        device: /dev/disk/by-partlabel/LIB
        format: ext4
        wipe_filesystem: false
    - name: opt
      mount:
        device: /dev/disk/by-partlabel/OPT
        format: ext4
        wipe_filesystem: false
#  links:
#    - filesystem: root
#      path: /opt
#      target: /var/lib/opt
systemd:
  units:
    # iSCSI daemon is used by Longhorn
    - name: iscsid.service
      enabled: true
    # Mount Local Disk as /var/lib for Rancher and Longhorn persistence
    - name: var-lib.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount as /var/lib
        Before=local-fs.target
        [Mount]
        What=/dev/disk/by-partlabel/LIB
        Where=/var/lib
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: opt.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount as /opt
        Before=local-fs.target
        [Mount]
        What=/dev/disk/by-partlabel/OPT
        Where=/opt
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: docker.service
      dropins:
        - name: 10-wait-docker.conf
          contents: |
            [Unit]
            After=var-lib.mount
            Requires=var-lib.mount
docker:
  flags:
    - --insecure-registry registry.localdomain:5000
